spring.application.name=finance-service
server.servlet.context-path=/finance-service
################################################################################################
# DB Configuration

spring.datasource.url=jdbc:postgresql://dpg-cnr747ud3nmc73970a90-a.singapore-postgres.render.com/finance_db?currentSchema=financedb
spring.datasource.username= finance_09i1_user
spring.datasource.password=BehnOH0YeswSDASfdecBgwKVn91Lw83F
spring.datasource.schema=financedb
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.minimum-idle=0
spring.datasource.hikari.initialization-fail-timeout=1
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation= true
spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto= update

##################################################################################################

spring.mvc.pathmatch.matching-strategy=ant_path_matcher


###########################################################################################

application.authorization.enabled = false