spring.application.name=finance-service
server.servlet.context-path=/finance-service
################################################################################################
# DB Configuration

spring.datasource.url=jdbc:postgresql://dpg-cs1cgd23esus739djce0-a.oregon-postgres.render.com/financedb_19u6
spring.datasource.username=financedb_19u6_user
spring.datasource.password=qs2ULl0jEV3eXFdFOdYyZVjZOiPwXgMM
spring.datasource.schema=financedb_19u6
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.minimum-idle=0
spring.datasource.hikari.initialization-fail-timeout=1
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation= true
spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto= update

##################################################################################################

spring.mvc.pathmatch.matching-strategy=ant_path_matcher


###########################################################################################

application.authorization.enabled = false
